"""Frozen reference outputs for the parity suite.

``tests/golden/<module>/<export>.json`` holds the immutable expected output for one pipeline
behaviour, produced over the frozen inputs in ``tests/fixtures/``. The ``test_*_parity.py``
modules assert that the pipeline still reproduces every value exactly, which makes this the
project's strongest regression signal: it pins observable output, not implementation detail.

These files are **committed and immutable**. They are not generated by this project and there is
no regeneration path — a golden changes only through a deliberate, reviewed edit. A parity test
that fails is therefore reporting a behaviour change in the pipeline, never a stale artifact.

JSON is the on-disk format because it is the only one that round-trips the null-vs-empty-string
distinction unambiguously (``null`` <-> ``None``, kept distinct from ``""``). Pipeline match keys
hinge on that distinction, so it is the correct default for the string-typed stages.

:data:`GOLDENS` declares the expected export names per module; ``test_goldens_present.py`` uses it
to fail loudly when a golden is missing, since the individual parity tests skip in that case and
would otherwise pass while comparing nothing.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

_THIS = Path(__file__).resolve()
REPO_ROOT = _THIS.parents[2]
FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures"
GOLDEN_ROOT = REPO_ROOT / "tests" / "golden"


@dataclass(frozen=True, slots=True)
class GoldenSet:
    """The frozen reference outputs for one module.

    Attributes:
        module: Sub-directory name under ``tests/golden/``.
        fixture: Input fixture path relative to ``tests/fixtures/``, or ``None`` for modules
            whose inputs are a workbook read from the corpus rather than a JSON vector.
        exports: Expected golden names, one per ``<export>.json`` file.
    """

    module: str
    fixture: str | None
    exports: tuple[str, ...]

    def golden_dir(self, golden_root: Path = GOLDEN_ROOT) -> Path:
        """Return the directory holding this module's golden files."""
        return golden_root / self.module

    def golden_paths(self, golden_root: Path = GOLDEN_ROOT) -> dict[str, Path]:
        """Return the ``export -> golden path`` mapping for this module."""
        target = self.golden_dir(golden_root)
        return {name: target / f"{name}.json" for name in self.exports}


GOLDENS: dict[str, GoldenSet] = {
    "conditional_group": GoldenSet(
        module="conditional_group",
        fixture="synthetic/conditional_group_inputs.json",
        exports=(
            "M_audit_affected_rows",
            "M_audit_column_source",
            "M_audit_column_target",
            "M_audit_dataset_name",
            "M_audit_execution_stage",
            "M_audit_execution_timestamp_utc",
            "M_audit_nrow",
            "M_audit_rule_file_identifier",
            "M_audit_value_source_raw",
            "M_audit_value_source_result",
            "M_audit_value_target_raw",
            "M_audit_value_target_result",
            "M_changed",
            "M_changed_columns",
            "M_commodity",
            "M_unit",
            "NM_audit_nrow",
            "NM_changed",
            "NM_changed_columns",
            "NM_commodity",
            "NM_unit",
            "SO_audit_nrow",
            "SO_changed",
            "SO_changed_columns",
            "SO_commodity",
            "SO_unit",
            "TO_audit_nrow",
            "TO_changed",
            "TO_changed_columns",
            "TO_commodity",
            "TO_unit",
        ),
    ),
    "data_audit": GoldenSet(
        module="data_audit",
        fixture="synthetic/data_audit_inputs.json",
        exports=(
            "findings_audit_column",
            "findings_audit_message",
            "findings_audit_type",
            "findings_row_index",
            "invalid_row_index",
            "parsed_value",
        ),
    ),
    "diagnostics": GoldenSet(
        module="diagnostics",
        fixture="synthetic/diagnostics_inputs.json",
        exports=(
            "cs_affected",
            "cs_column_target",
            "cs_loop",
            "cs_value_source",
            "cs_value_target",
            "cu_affected",
            "cu_column_source",
            "cu_nrow",
            "cu_value_source_raw",
            "ss_affected",
            "ss_commodity",
            "ss_unit_target",
            "su_affected",
            "su_commodity",
            "su_nrow",
            "su_unit_source",
        ),
    ),
    "export_lists": GoldenSet(
        module="export_lists",
        fixture="synthetic/export_lists_inputs.json",
        exports=(
            "export_columns",
            "sheets_commodity",
            "sheets_continent",
            "sheets_polity",
            "sheets_unit",
            "union_columns",
            "uniq_clean_commodity",
            "uniq_clean_continent",
            "uniq_clean_polity",
            "uniq_clean_unit",
            "uniq_harmonize_commodity",
            "uniq_harmonize_continent",
            "uniq_harmonize_polity",
            "uniq_harmonize_unit",
            "uniq_normalize_commodity",
            "uniq_normalize_continent",
            "uniq_normalize_polity",
            "uniq_normalize_unit",
            "uniq_raw_commodity",
            "uniq_raw_continent",
            "uniq_raw_polity",
            "uniq_raw_unit",
        ),
    ),
    "export_processed_data": GoldenSet(
        module="export_processed_data",
        fixture="synthetic/export_processed_inputs.json",
        exports=("tsv_hex",),
    ),
    "file_metadata": GoldenSet(
        module="file_metadata",
        fixture="synthetic/file_metadata_inputs.json",
        exports=(
            "commodity",
            "error_message",
            "file_name",
            "file_path",
            "is_ascii",
            "yearbook",
        ),
    ),
    "header_normalization": GoldenSet(
        module="header_normalization",
        fixture="synthetic/header_names_inputs.json",
        exports=(
            "normalize",
            "renames_dedup_new",
            "renames_dedup_old",
            "renames_guarded_new",
            "renames_guarded_old",
            "renames_main_new",
            "renames_main_old",
            "validate_dups",
        ),
    ),
    "import_stage": GoldenSet(
        module="import_stage",
        fixture=None,
        exports=(
            "commodity",
            "continent",
            "data_columns",
            "data_nrow",
            "document",
            "footnotes",
            "hemisphere",
            "notes",
            "polity",
            "reading_errors",
            "unit",
            "validation_errors",
            "value",
            "variable",
            "warnings",
            "year",
            "yearbook",
        ),
    ),
    "layer_batch": GoldenSet(
        module="layer_batch",
        fixture="synthetic/layer_batch_inputs.json",
        exports=(
            "clean_columns",
            "clean_commodity",
            "clean_converged",
            "clean_matched",
            "clean_passes",
            "clean_stop_reason",
            "clean_unit",
            "clean_value",
            "harm_columns",
            "harm_commodity",
            "harm_converged",
            "harm_matched",
            "harm_passes",
            "harm_stop_reason",
            "harm_unit",
            "harm_value",
        ),
    ),
    "matching": GoldenSet(
        module="matching",
        fixture="synthetic/matching_values_inputs.json",
        exports=(
            "change_count",
            "concat_merge",
            "decode_target",
            "encode_key",
            "encode_key_raw",
            "encode_target",
            "match_plain",
            "match_tokenized",
        ),
    ),
    "postpro_stage": GoldenSet(
        module="postpro_stage",
        fixture="synthetic/postpro_stage_input.json",
        exports=(
            "clean_columns",
            "clean_commodity",
            "clean_continent",
            "clean_converged",
            "clean_document",
            "clean_footnotes",
            "clean_hemisphere",
            "clean_matched",
            "clean_notes",
            "clean_nrow",
            "clean_passes",
            "clean_polity",
            "clean_stop_reason",
            "clean_unit",
            "clean_value",
            "clean_variable",
            "clean_year",
            "clean_yearbook",
            "harmonize_columns",
            "harmonize_commodity",
            "harmonize_continent",
            "harmonize_converged",
            "harmonize_document",
            "harmonize_footnotes",
            "harmonize_hemisphere",
            "harmonize_matched",
            "harmonize_notes",
            "harmonize_nrow",
            "harmonize_passes",
            "harmonize_polity",
            "harmonize_stop_reason",
            "harmonize_unit",
            "harmonize_value",
            "harmonize_variable",
            "harmonize_year",
            "harmonize_yearbook",
            "normalize_columns",
            "normalize_commodity",
            "normalize_continent",
            "normalize_document",
            "normalize_footnotes",
            "normalize_hemisphere",
            "normalize_notes",
            "normalize_nrow",
            "normalize_polity",
            "normalize_unit",
            "normalize_value",
            "normalize_variable",
            "normalize_year",
            "normalize_yearbook",
        ),
    ),
    "processing": GoldenSet(
        module="processing",
        fixture=None,
        exports=(
            "commodity",
            "continent",
            "document",
            "footnotes",
            "hemisphere",
            "long_columns",
            "long_nrow",
            "notes",
            "polity",
            "unit",
            "value",
            "variable",
            "year",
            "yearbook",
        ),
    ),
    "rule_table_csv": GoldenSet(
        module="rule_table_csv",
        fixture=None,
        exports=(
            "column_source",
            "columns",
            "nrow",
            "value_source_raw",
            "value_target_raw",
        ),
    ),
    "schema_validation": GoldenSet(
        module="schema_validation",
        fixture="synthetic/schema_validation_inputs.json",
        exports=(
            "cA_column_source",
            "cA_columns",
            "cA_source_value_column_present",
            "cA_value_source",
            "cB_columns",
            "cB_source_value_column_present",
            "cB_value_source",
            "dict_flat_column_source",
            "dict_flat_column_target",
            "dict_flat_value_source_raw",
            "dict_flat_value_target",
            "dict_ngroups",
            "validate_duplicate_aborts",
            "validate_missing_column_aborts",
            "validate_valid_aborts",
        ),
    ),
    "sheet_read": GoldenSet(
        module="sheet_read",
        fixture=None,
        exports=(
            "columns",
            "continent",
            "footnotes",
            "hemisphere",
            "nrow",
            "polity",
            "unit",
            "variable",
            "y1934_1938",
            "y1946",
            "y1947",
            "y1948",
        ),
    ),
    "standardize": GoldenSet(
        module="standardize",
        fixture="synthetic/standardize_inputs.json",
        exports=(
            "commodity",
            "matched",
            "mrc_affected",
            "mrc_applied",
            "mrc_effective",
            "mrc_nrow",
            "unit",
            "unmatched",
            "value",
        ),
    ),
    "standardize_agg": GoldenSet(
        module="standardize_agg",
        fixture="synthetic/standardize_agg_inputs.json",
        exports=(
            "agg_commodity",
            "agg_nrow",
            "agg_value",
            "audit_affected",
            "audit_commodity",
            "audit_effective",
            "audit_nrow",
            "audit_target",
        ),
    ),
    "target_apply": GoldenSet(
        module="target_apply",
        fixture="synthetic/target_apply_inputs.json",
        exports=(
            "A_applied",
            "A_changed",
            "A_ev_nrow",
            "A_unit",
            "B_applied",
            "B_changed",
            "B_ev_candidate_count",
            "B_ev_candidate_values",
            "B_ev_column_source",
            "B_ev_column_target",
            "B_ev_dataset_name",
            "B_ev_execution_stage",
            "B_ev_nrow",
            "B_ev_row_id",
            "B_ev_rule_file_identifier",
            "B_ev_selected_value",
            "B_ev_unique_candidate_count",
            "B_unit",
            "C_applied",
            "C_changed",
            "C_ev_nrow",
            "C_notes",
            "D_applied",
            "D_changed",
            "D_ev_nrow",
            "D_notes",
        ),
    ),
    "transform": GoldenSet(
        module="transform",
        fixture=None,
        exports=(
            "commodity",
            "continent",
            "document",
            "footnotes",
            "hemisphere",
            "long_columns",
            "long_nrow",
            "notes",
            "polity",
            "unit",
            "value",
            "variable",
            "year",
            "yearbook",
        ),
    ),
    "utilities": GoldenSet(
        module="utilities",
        fixture=None,
        exports=(
            "diag_empty_matched_count",
            "diag_empty_messages",
            "diag_empty_status",
            "diag_empty_unmatched_count",
            "diag_matched_matched_count",
            "diag_matched_messages",
            "diag_matched_status",
            "diag_matched_unmatched_count",
            "rr_column_source",
            "rr_column_target",
            "rr_columns",
            "rr_nrow",
            "rr_value_source",
            "rr_value_source_raw",
            "rr_value_target",
            "rr_value_target_raw",
        ),
    ),
    "validate": GoldenSet(
        module="validate",
        fixture="synthetic/validate_long_inputs.json",
        exports=(
            "data_document",
            "data_value",
            "errors",
        ),
    ),
}
